[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 app_static.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "never"

[environment]
PORT = "5001"
FLASK_ENV = "production"
